import { notFound } from "next/navigation";

import { db } from "@/src/lib/db";

export default async function PublicInvoicePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const invoice = await db.invoice.findUnique({ where: { printableToken: token }, select: { invoiceNumber: true, status: true, subtotal: true, discount: true, tax: true, total: true, issuedAt: true, dueAt: true, items: { select: { id: true, description: true, quantity: true, lineTotal: true } }, payments: { select: { amount: true } }, job: { select: { customer: { select: { name: true } } } } } });
  if (!invoice) notFound();
  const paid = invoice.payments.reduce((sum, payment) => sum + Number(payment.amount), 0);
  return <main className="min-h-screen bg-muted/30 px-4 py-10"><article className="mx-auto max-w-2xl bg-background p-6 shadow-sm ring-1 ring-foreground/10"><p className="text-sm font-medium text-primary">AC BILL</p><h1 className="mt-1 text-2xl font-semibold">Invoice {invoice.invoiceNumber}</h1><div className="mt-8 flex justify-between border-y py-5 text-sm"><div><p className="text-muted-foreground">Customer</p><p className="mt-1 font-medium">{invoice.job.customer.name}</p></div><div className="text-right"><p className="text-muted-foreground">Issued</p><p className="mt-1">{invoice.issuedAt?.toLocaleDateString("en-MY", { dateStyle: "medium" }) ?? "Pending"}</p></div></div><table className="mt-6 w-full text-sm"><thead className="border-b text-left text-muted-foreground"><tr><th className="py-3 font-medium">Description</th><th className="py-3 text-right font-medium">Qty</th><th className="py-3 text-right font-medium">Amount</th></tr></thead><tbody>{invoice.items.map((item) => <tr key={item.id} className="border-b"><td className="py-3">{item.description}</td><td className="py-3 text-right">{Number(item.quantity)}</td><td className="py-3 text-right">RM {Number(item.lineTotal).toFixed(2)}</td></tr>)}</tbody></table><div className="ml-auto mt-6 grid max-w-xs gap-2 text-sm"><Summary label="Subtotal" value={Number(invoice.subtotal)} />{Number(invoice.discount) ? <Summary label="Discount" value={-Number(invoice.discount)} /> : null}{Number(invoice.tax) ? <Summary label="Tax" value={Number(invoice.tax)} /> : null}<div className="flex justify-between border-t pt-2 text-base font-semibold"><span>Total</span><span>RM {Number(invoice.total).toFixed(2)}</span></div><Summary label="Paid" value={paid} /><div className="flex justify-between font-medium"><span>Balance due</span><span>RM {Math.max(0, Number(invoice.total) - paid).toFixed(2)}</span></div></div></article></main>;
}

function Summary({ label, value }: { label: string; value: number }) { return <div className="flex justify-between"><span className="text-muted-foreground">{label}</span><span>RM {value.toFixed(2)}</span></div>; }
